name: 'msmarco_PR'
data_folder: 'datasets/10k_checkpoint/'
train_data: 'train.json'
train_documents: 'documents.json'
dev_data: 'dev.json'
dev_documents: 'documents.json'
test_data: 'test.json'
test_documents: 'documents.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities.txt'
word_emb_file: null 
entity_emb_file: null 
entity_kge_file: null 
relation_emb_file: null 
relation_kge_file: null 

to_save_model: False
save_model_file: "model/repro/10k/model_saved"
pred_file: "model/repro/10k/pred_saved"
load_model_file: null

# graph options
fact_dropout: 0.0
use_kb: True
use_doc: True

num_layer: 3
max_query_word: 50
max_document_word: 80

entity_dim: 80
word_dim: 80
kge_dim: 80
pagerank_lambda: 0.8
fact_scale: 1
use_inverse_relation: True

# optimization
num_epoch: 50
gradient_clip: 1
learning_rate: 0.01
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False

train_batch_size: 20
testndev_batch_size: 5
